### ISSUE TITLE
Run migrate through docker container

### ISSUE THREAD

**Issue by syahnur197** [B-Open/jobalert#17]
> > > ```shell
> > > migrate -path . -database 'mysql://root@tcp(localhost:3306)/jobalert' up
> > > ```
> > 
> > 
> > I don't think this would work in the current docker compose file since db container's port are not forwarded to host's port
> 
> Yes, I was trying to get migrate to work within the docker container, but so far I managed to get it installed but not able to connect to the database.

You need to expose the port to the host machine, just like how you expose the api port, you might just need to add the following code in your docker-compose.yml

```yaml
db:
    image: mysql:8.0
    volumes:
        - "jobalert_db:/var/lib/mysql"
    ports:
        # forwarding container's port 3306 to host's port 3306
        - "3306:3306"
        # I guess the above line won't work in your PC since you have a MySQL service running in your PC
        # your PC's port 3306 will already been used by your PC's MySQL
        # for that you need to bind the container's port 3306 to your PC's port 3307
        # in theory this db url would work: 'mysql://root@tcp(localhost:3307)/jobalert'
        # it's either one of these two, not really sure the exact arrangement 
        # is it `"container_port:host_port"` or `"host_port:container_port"`
        - "3307:3306"
        - "3306:3307"  
    restart: always
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_DATABASE: "jobalert"
````

another way you could do is to create another container (example name migrate), we can use alpine or ubuntu image, install go-migrate in the container using Dockerfile, in that case we can ssh into the container or run:
 
`docker-compose exec migrate -path . -database 'mysql://root@tcp(db:3306)/jobalert' up`

tbh I prefer if we could have the latter approach than the former as we don't have to mess with the host's port

_Originally posted by @syahnur197 in https://github.com/B-Open/jobalert/issues/16#issuecomment-950260209_
